disabled_rules: # rule identifiers to exclude from running
  - legacy_constructor
  - vertical_parameter_alignment
  - identifier_name
  - trailing_newline
  - control_statement
  - trailing_whitespace
  - leading_whitespace
  - operator_whitespace
  - mark
  - orphaned_doc_comment
  - cyclomatic_complexity
  - comment_spacing
